// src/components/Map.svelte
<script>

</script>

<style>
  .map {
    margin: 0;
    padding: 0;
    height: 50rem;
    width: 100vw;
    background-color: darkslategray;
  }
</style>

<div class="map">
  <iframe
    title="google-maps-topola-skies"
    width="100%"
    height="110%"
    frameborder="0"
    style="border:0"
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11592.268976996691!2d28.266040284689765!3d43.41742174951944!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40a4e5e374a63d0d%3A0x750a25b2a1ca3f72!2sTopola+Skies!5e0!3m2!1sen!2sfi!4v1563032844807!5m2!1sen!2sfi"
    allowfullscreen />
</div>

// components/Map.tsx
import styled from 'styled-components';

const Map: React.FC = () => (
  <iframe
    frameBorder="0"
    src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJDT2mdOPlpEARcj_KobIlCnU&key=AIzaSyAPM1cc0bHAfhVVDlVtBuPMwAcS7-fBdWc"
    title="Topola Skies - Google Maps"
    allowFullScreen
  />
);

const StyledMap: React.FC = styled(Map)`
  display: block;
  width: calc(100% - 4rem);
  height: 40vh;
  border: 1px solid ${(props): string => props.theme.lightgrey};
  margin: auto;
`;

export default StyledMap;
